---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolors
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victormilk/aula-app-of-apps
    targetRevision: HEAD
    path: webcolors
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true