---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color-01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victormilk/web-color-deploy
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: web-color-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true